---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# epiworldR

<!-- badges: start -->
<!-- badges: end -->

This R package is a wrapper of the C++ library [epiworld](https://github.com/UofUEpi/epiworld). 
It provides a general framework for modeling disease transmission using Agent-Based Models.

## Installation

You can install the development version of epiworldR from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("UofUEpi/epiworldR")
```

## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
library(epiworldR)

# Creating a SIR model
sir <- ModelSIR(
  name = "COVID-19",
  prevalence = .01,
  infectiousness = .9,
  recovery = .3
  )

# Adding a Small world population 
agents_smallworld(
  sir,
  n = 100000,
  k = 5,
  d = FALSE,
  p = .01
  )

# Initializing 
init(sir, days = 100, seed = 1912)

# Running and printing
run(sir)
sir
```

Visualizing the outputs

```{r}
x <- get_hist_total(sir)
x$counts <- x$counts/1000
x <- x[x$dates < 50,]

with(
  x[x$status == "Susceptible",],
  plot(
    x = dates, y = counts, type = "l", col = "blue", ylim = range(x$counts),
    ylab = "Population (thousands)", xlab = "days", main = "SIR model")
  )

with(
  x[x$status == "Infected",],
  lines(x = dates, y = counts, col = "red")
  )

with(
  x[x$status == "Recovered",],
  lines(x = dates, y = counts, col = "darkgreen")
  )

legend(
  "right",
  legend = c("Susceptible", "Infected", "Removed"),
  col    = c("blue", "red", "darkgreen"),
  lty    = 1,
  lwd    = 2,
  bty    = "n"
  )

```

