// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// sum_function.cpp
double sum_cpp(doubles x);
extern "C" SEXP _epiworldR_sum_cpp(SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(sum_cpp(cpp11::as_cpp<cpp11::decay_t<doubles>>(x)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_epiworldR_sum_cpp", (DL_FUNC) &_epiworldR_sum_cpp, 1},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_epiworldR(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
