# Generated by cpp11: do not edit by hand

queuing_on_cpp <- function(model, model_class) {
  .Call(`_epiworldR_queuing_on_cpp`, model, model_class)
}

queuing_off_cpp <- function(model, model_class) {
  .Call(`_epiworldR_queuing_off_cpp`, model, model_class)
}

get_hist_total_cpp <- function(model, model_class) {
  .Call(`_epiworldR_get_hist_total_cpp`, model, model_class)
}

get_transition_probability_cpp <- function(model, model_class) {
  .Call(`_epiworldR_get_transition_probability_cpp`, model, model_class)
}

get_status_cpp <- function(model, model_class) {
  .Call(`_epiworldR_get_status_cpp`, model, model_class)
}

get_reproductive_number_cpp <- function(model, model_class) {
  .Call(`_epiworldR_get_reproductive_number_cpp`, model, model_class)
}

init_cpp <- function(m, days, seed) {
  .Call(`_epiworldR_init_cpp`, m, days, seed)
}

print_cpp <- function(m) {
  .Call(`_epiworldR_print_cpp`, m)
}

agents_smallworld_cpp <- function(m, n, k, d, p) {
  .Call(`_epiworldR_agents_smallworld_cpp`, m, n, k, d, p)
}

run_cpp <- function(m) {
  .Call(`_epiworldR_run_cpp`, m)
}

ModelSEIR_cpp <- function(name, prevalence, infectiousness, incubation_days, recovery) {
  .Call(`_epiworldR_ModelSEIR_cpp`, name, prevalence, infectiousness, incubation_days, recovery)
}

ModelSEIRCONN_cpp <- function(name, n, prevalence, reproductive_number, prob_transmission, incubation_days, prob_recovery) {
  .Call(`_epiworldR_ModelSEIRCONN_cpp`, name, n, prevalence, reproductive_number, prob_transmission, incubation_days, prob_recovery)
}

print_seirconn <- function(m) {
  .Call(`_epiworldR_print_seirconn`, m)
}

run_seirconn <- function(m) {
  .Call(`_epiworldR_run_seirconn`, m)
}

ModelSIR_cpp <- function(name, prevalence, infectiousness, recovery) {
  .Call(`_epiworldR_ModelSIR_cpp`, name, prevalence, infectiousness, recovery)
}

ModelSIRCONN_cpp <- function(name, n, prevalence, reproductive_number, prob_transmission, prob_recovery) {
  .Call(`_epiworldR_ModelSIRCONN_cpp`, name, n, prevalence, reproductive_number, prob_transmission, prob_recovery)
}

ModelSIS_cpp <- function(name, prevalence, infectiousness, recovery) {
  .Call(`_epiworldR_ModelSIS_cpp`, name, prevalence, infectiousness, recovery)
}

ModelSURV_cpp <- function(name, prevalence, efficacy_vax, latent_period, prob_symptoms, prop_vaccinated, prop_vax_redux_transm, infect_period, prop_vax_redux_infect, surveillance_prob, prob_transmission, prob_death, prob_noreinfect) {
  .Call(`_epiworldR_ModelSURV_cpp`, name, prevalence, efficacy_vax, latent_period, prob_symptoms, prop_vaccinated, prop_vax_redux_transm, infect_period, prop_vax_redux_infect, surveillance_prob, prob_transmission, prob_death, prob_noreinfect)
}

virus_cpp <- function(name, post_immunity, prob_infecting, prob_recovery, prob_death) {
  .Call(`_epiworldR_virus_cpp`, name, post_immunity, prob_infecting, prob_recovery, prob_death)
}

virus_set_status_cpp <- function(v, init, end, removed) {
  .Call(`_epiworldR_virus_set_status_cpp`, v, init, end, removed)
}

add_virus_cpp <- function(m, v, preval) {
  .Call(`_epiworldR_add_virus_cpp`, m, v, preval)
}

add_virus_n_cpp <- function(m, v, preval) {
  .Call(`_epiworldR_add_virus_n_cpp`, m, v, preval)
}
