# Generated by cpp11: do not edit by hand

globalaction_tool_logit_cpp <- function(tool, vars, coefs) {
  .Call(`_epiworldR_globalaction_tool_logit_cpp`, tool, vars, coefs)
}

globalaction_tool_cpp <- function(tool, prob) {
  .Call(`_epiworldR_globalaction_tool_cpp`, tool, prob)
}

globalaction_set_param_cpp <- function(param, value) {
  .Call(`_epiworldR_globalaction_set_param_cpp`, param, value)
}

add_global_action_cpp <- function(model, action, date) {
  .Call(`_epiworldR_add_global_action_cpp`, model, action, date)
}

get_agents_cpp <- function(model) {
  .Call(`_epiworldR_get_agents_cpp`, model)
}

get_agent_cpp <- function(agents, i) {
  .Call(`_epiworldR_get_agent_cpp`, agents, i)
}

print_agent_cpp <- function(agent, model, compressed) {
  .Call(`_epiworldR_print_agent_cpp`, agent, model, compressed)
}

get_state_agent_cpp <- function(agent) {
  .Call(`_epiworldR_get_state_agent_cpp`, agent)
}

get_hist_total_cpp <- function(model) {
  .Call(`_epiworldR_get_hist_total_cpp`, model)
}

get_hist_variant_cpp <- function(model) {
  .Call(`_epiworldR_get_hist_variant_cpp`, model)
}

get_hist_tool_cpp <- function(model) {
  .Call(`_epiworldR_get_hist_tool_cpp`, model)
}

get_transition_probability_cpp <- function(model) {
  .Call(`_epiworldR_get_transition_probability_cpp`, model)
}

get_hist_transition_matrix_cpp <- function(model, skip_zeros) {
  .Call(`_epiworldR_get_hist_transition_matrix_cpp`, model, skip_zeros)
}

get_reproductive_number_cpp <- function(model) {
  .Call(`_epiworldR_get_reproductive_number_cpp`, model)
}

get_transmissions_cpp <- function(model) {
  .Call(`_epiworldR_get_transmissions_cpp`, model)
}

ModelSURV_cpp <- function(name, prevalence, efficacy_vax, latent_period, prob_symptoms, prop_vaccinated, prop_vax_redux_transm, infect_period, prop_vax_redux_infect, surveillance_prob, prob_transmission, prob_death, prob_noreinfect) {
  .Call(`_epiworldR_ModelSURV_cpp`, name, prevalence, efficacy_vax, latent_period, prob_symptoms, prop_vaccinated, prop_vax_redux_transm, infect_period, prop_vax_redux_infect, surveillance_prob, prob_transmission, prob_death, prob_noreinfect)
}

ModelSEIR_cpp <- function(name, prevalence, infectiousness, incubation_days, recovery) {
  .Call(`_epiworldR_ModelSEIR_cpp`, name, prevalence, infectiousness, incubation_days, recovery)
}

ModelSIS_cpp <- function(name, prevalence, infectiousness, recovery) {
  .Call(`_epiworldR_ModelSIS_cpp`, name, prevalence, infectiousness, recovery)
}

ModelSIRCONN_cpp <- function(name, n, prevalence, contact_rate, prob_transmission, prob_recovery) {
  .Call(`_epiworldR_ModelSIRCONN_cpp`, name, n, prevalence, contact_rate, prob_transmission, prob_recovery)
}

ModelSIR_cpp <- function(name, prevalence, infectiousness, recovery) {
  .Call(`_epiworldR_ModelSIR_cpp`, name, prevalence, infectiousness, recovery)
}

ModelSEIRCONN_cpp <- function(name, n, prevalence, contact_rate, prob_transmission, incubation_days, prob_recovery) {
  .Call(`_epiworldR_ModelSEIRCONN_cpp`, name, n, prevalence, contact_rate, prob_transmission, incubation_days, prob_recovery)
}

ModelSIRLogit_cpp <- function(vname, data, ncols, coefs_infect, coefs_recover, coef_infect_cols, coef_recover_cols, prob_infection, prob_recovery, prevalence) {
  .Call(`_epiworldR_ModelSIRLogit_cpp`, vname, data, ncols, coefs_infect, coefs_recover, coef_infect_cols, coef_recover_cols, prob_infection, prob_recovery, prevalence)
}

print_cpp <- function(m) {
  .Call(`_epiworldR_print_cpp`, m)
}

agents_smallworld_cpp <- function(m, n, k, d, p) {
  .Call(`_epiworldR_agents_smallworld_cpp`, m, n, k, d, p)
}

agents_from_edgelist_cpp <- function(m, source, target, size, directed) {
  .Call(`_epiworldR_agents_from_edgelist_cpp`, m, source, target, size, directed)
}

run_cpp <- function(m, ndays, seed) {
  .Call(`_epiworldR_run_cpp`, m, ndays, seed)
}

make_saver_cpp <- function(fn, total_hist, variant_info, variant_hist, tool_info, tool_hist, transmission, transition, reproductive, generation) {
  .Call(`_epiworldR_make_saver_cpp`, fn, total_hist, variant_info, variant_hist, tool_info, tool_hist, transmission, transition, reproductive, generation)
}

run_multiple_cpp <- function(m, ndays, nsims, seed, saver, reset, verbose, nthreads) {
  .Call(`_epiworldR_run_multiple_cpp`, m, ndays, nsims, seed, saver, reset, verbose, nthreads)
}

queuing_on_cpp <- function(model) {
  .Call(`_epiworldR_queuing_on_cpp`, model)
}

queuing_off_cpp <- function(model) {
  .Call(`_epiworldR_queuing_off_cpp`, model)
}

get_param_cpp <- function(model, pname) {
  .Call(`_epiworldR_get_param_cpp`, model, pname)
}

set_param_cpp <- function(model, pname, val) {
  .Call(`_epiworldR_set_param_cpp`, model, pname, val)
}

set_name_cpp <- function(model, mname) {
  .Call(`_epiworldR_set_name_cpp`, model, mname)
}

get_name_cpp <- function(model) {
  .Call(`_epiworldR_get_name_cpp`, model)
}

get_states_cpp <- function(model) {
  .Call(`_epiworldR_get_states_cpp`, model)
}

verbose_on_cpp <- function(model) {
  .Call(`_epiworldR_verbose_on_cpp`, model)
}

verbose_off_cpp <- function(model) {
  .Call(`_epiworldR_verbose_off_cpp`, model)
}

get_n_variants_cpp <- function(model) {
  .Call(`_epiworldR_get_n_variants_cpp`, model)
}

get_n_tools_cpp <- function(model) {
  .Call(`_epiworldR_get_n_tools_cpp`, model)
}

get_ndays_cpp <- function(model) {
  .Call(`_epiworldR_get_ndays_cpp`, model)
}

get_n_replicates_cpp <- function(model) {
  .Call(`_epiworldR_get_n_replicates_cpp`, model)
}

size_cpp <- function(model) {
  .Call(`_epiworldR_size_cpp`, model)
}

set_agents_data_cpp <- function(model, data, ncols) {
  .Call(`_epiworldR_set_agents_data_cpp`, model, data, ncols)
}

get_agents_data_ncols_cpp <- function(model) {
  .Call(`_epiworldR_get_agents_data_ncols_cpp`, model)
}

get_virus_model_cpp <- function(model, virus_pos) {
  .Call(`_epiworldR_get_virus_model_cpp`, model, virus_pos)
}

get_tool_model_cpp <- function(model, tool_pos) {
  .Call(`_epiworldR_get_tool_model_cpp`, model, tool_pos)
}

tool_cpp <- function(name, susceptibility_reduction, transmission_reduction, recovery_enhancer, death_reduction) {
  .Call(`_epiworldR_tool_cpp`, name, susceptibility_reduction, transmission_reduction, recovery_enhancer, death_reduction)
}

add_tool_cpp <- function(m, t, preval) {
  .Call(`_epiworldR_add_tool_cpp`, m, t, preval)
}

add_tool_n_cpp <- function(m, t, preval) {
  .Call(`_epiworldR_add_tool_n_cpp`, m, t, preval)
}

rm_tool_cpp <- function(m, tool_pos) {
  .Call(`_epiworldR_rm_tool_cpp`, m, tool_pos)
}

tool_fun_logit_cpp <- function(vars, coefs, model) {
  .Call(`_epiworldR_tool_fun_logit_cpp`, vars, coefs, model)
}

set_transmission_reduction_cpp <- function(tool, prob) {
  .Call(`_epiworldR_set_transmission_reduction_cpp`, tool, prob)
}

set_transmission_reduction_ptr_cpp <- function(tool, model, param) {
  .Call(`_epiworldR_set_transmission_reduction_ptr_cpp`, tool, model, param)
}

set_transmission_reduction_fun_cpp <- function(tool, model, tfun) {
  .Call(`_epiworldR_set_transmission_reduction_fun_cpp`, tool, model, tfun)
}

set_susceptibility_reduction_cpp <- function(tool, prob) {
  .Call(`_epiworldR_set_susceptibility_reduction_cpp`, tool, prob)
}

set_susceptibility_reduction_ptr_cpp <- function(tool, model, param) {
  .Call(`_epiworldR_set_susceptibility_reduction_ptr_cpp`, tool, model, param)
}

set_susceptibility_reduction_fun_cpp <- function(tool, model, tfun) {
  .Call(`_epiworldR_set_susceptibility_reduction_fun_cpp`, tool, model, tfun)
}

set_recovery_enhancer_cpp <- function(tool, prob) {
  .Call(`_epiworldR_set_recovery_enhancer_cpp`, tool, prob)
}

set_recovery_enhancer_ptr_cpp <- function(tool, model, param) {
  .Call(`_epiworldR_set_recovery_enhancer_ptr_cpp`, tool, model, param)
}

set_recovery_enhancer_fun_cpp <- function(tool, model, tfun) {
  .Call(`_epiworldR_set_recovery_enhancer_fun_cpp`, tool, model, tfun)
}

set_death_reduction_cpp <- function(tool, prob) {
  .Call(`_epiworldR_set_death_reduction_cpp`, tool, prob)
}

set_death_reduction_ptr_cpp <- function(tool, model, param) {
  .Call(`_epiworldR_set_death_reduction_ptr_cpp`, tool, model, param)
}

set_death_reduction_fun_cpp <- function(tool, model, tfun) {
  .Call(`_epiworldR_set_death_reduction_fun_cpp`, tool, model, tfun)
}

get_name_tool_cpp <- function(tool) {
  .Call(`_epiworldR_get_name_tool_cpp`, tool)
}

set_name_tool_cpp <- function(tool, name) {
  .Call(`_epiworldR_set_name_tool_cpp`, tool, name)
}

print_tool_cpp <- function(t) {
  .Call(`_epiworldR_print_tool_cpp`, t)
}

virus_cpp <- function(name, prob_infecting, prob_recovery, prob_death, post_immunity) {
  .Call(`_epiworldR_virus_cpp`, name, prob_infecting, prob_recovery, prob_death, post_immunity)
}

virus_set_state_cpp <- function(v, init, end, removed) {
  .Call(`_epiworldR_virus_set_state_cpp`, v, init, end, removed)
}

add_virus_cpp <- function(m, v, preval) {
  .Call(`_epiworldR_add_virus_cpp`, m, v, preval)
}

add_virus_n_cpp <- function(m, v, preval) {
  .Call(`_epiworldR_add_virus_n_cpp`, m, v, preval)
}

rm_virus_cpp <- function(m, virus_pos) {
  .Call(`_epiworldR_rm_virus_cpp`, m, virus_pos)
}

print_virus_cpp <- function(v) {
  .Call(`_epiworldR_print_virus_cpp`, v)
}

virus_fun_logit_cpp <- function(vars, coefs, model) {
  .Call(`_epiworldR_virus_fun_logit_cpp`, vars, coefs, model)
}

set_prob_infecting_cpp <- function(virus, prob) {
  .Call(`_epiworldR_set_prob_infecting_cpp`, virus, prob)
}

set_prob_infecting_ptr_cpp <- function(virus, model, param) {
  .Call(`_epiworldR_set_prob_infecting_ptr_cpp`, virus, model, param)
}

set_prob_infecting_fun_cpp <- function(virus, model, vfun) {
  .Call(`_epiworldR_set_prob_infecting_fun_cpp`, virus, model, vfun)
}

set_prob_recovery_cpp <- function(virus, prob) {
  .Call(`_epiworldR_set_prob_recovery_cpp`, virus, prob)
}

set_prob_recovery_ptr_cpp <- function(virus, model, param) {
  .Call(`_epiworldR_set_prob_recovery_ptr_cpp`, virus, model, param)
}

set_prob_recovery_fun_cpp <- function(virus, model, vfun) {
  .Call(`_epiworldR_set_prob_recovery_fun_cpp`, virus, model, vfun)
}

set_prob_death_cpp <- function(virus, prob) {
  .Call(`_epiworldR_set_prob_death_cpp`, virus, prob)
}

set_prob_death_ptr_cpp <- function(virus, model, param) {
  .Call(`_epiworldR_set_prob_death_ptr_cpp`, virus, model, param)
}

set_prob_death_fun_cpp <- function(virus, model, vfun) {
  .Call(`_epiworldR_set_prob_death_fun_cpp`, virus, model, vfun)
}

get_name_virus_cpp <- function(virus) {
  .Call(`_epiworldR_get_name_virus_cpp`, virus)
}

set_name_virus_cpp <- function(virus, name) {
  .Call(`_epiworldR_set_name_virus_cpp`, virus, name)
}
