# Generated by cpp11: do not edit by hand

ModelSIR <- function(name, prevalence, infectiousness, recovery) {
  .Call(`_epiworldR_ModelSIR`, name, prevalence, infectiousness, recovery)
}

init <- function(m, days, seed) {
  .Call(`_epiworldR_init`, m, days, seed)
}

print <- function(m) {
  .Call(`_epiworldR_print`, m)
}

agents_smallworld <- function(m, n, k, d, p) {
  .Call(`_epiworldR_agents_smallworld`, m, n, k, d, p)
}

run <- function(m) {
  .Call(`_epiworldR_run`, m)
}

sum_cpp <- function(x) {
  .Call(`_epiworldR_sum_cpp`, x)
}
